default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: hackmidwest_can_eat_this_development

test: &test
  <<: *default
  database: hackmidwest_can_eat_this_test

