# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62eb3c53baa01c2027c3f1ce7a34609b869bf006b3e269131a24717b13da7c2ff134b865e58d62e7bab9e7f94b376fabfce84e77766666e31e2a3672780a5afd

test:
  secret_key_base: 9c627671fe8f58e81ed384d4cf275a9a12c333a4154f2a6534cf3bd47ffacde5dd96b2be7f03e30e25df08f989f64ae58e04d9005d681315ff5564a987241f48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
